### ISSUE TITLE
Unify code formatting in the Native module

### ISSUE THREAD

**Issue by w0rm** [elm-community/elm-webgl#18]
I'm not sure if there is a preferred way to format JavaScript, I am happy with any coding style but it has to be consistent.

Perhaps we can as well add an eslint config or something.

**Comment by nphollon** [comment]
I think this is a fine idea. Most of the original JS was written by @johnpmayer... maybe he has a suggested style?

The style I use personally is the strictest settings for [JSHint](http://jshint.com/docs/options/), but it looks like the tool has changed a bit since the last time I used it.

**Comment by w0rm** [comment]
I added an eslint config for the most recent version of eslint. The cool thing about it, is that you can run `eslint src/Native --fix` and it will fix the formatting itself.

It also discovered a bug in `throw error('No info available for: ' + attribute.type);` where `error` should be `new Error`
