### ISSUE TITLE
Examples lead to 404

### ISSUE THREAD

**Issue by bstro** [elm-community/elm-webgl#21]
The examples currently linked to from the repository `README.md` lead to a 404. Do these exist somewhere else now?

<img width="579" alt="screen shot 2016-06-05 at 10 24 12 pm" src="https://cloud.githubusercontent.com/assets/627290/15812651/5d3987c6-2b6c-11e6-9d68-c5df29ec758c.png">

**Comment by Ryan1729** [comment]
I don't know if there are any hosted versions but the code for the examples is included in the examples folder in the repo.

**Comment by bstro** [comment]
Ah, right. Thanks!
