### ISSUE TITLE
Support the advanced mode of google closure compiler

### ISSUE THREAD

**Issue by w0rm** [elm-community/elm-webgl#35]
I tried to apply google closure compiler on my webgl game, however this didn't work well and got me some JavaScript error. I believe this has to be investigated further and hopefully fixed.

**Comment by w0rm** [comment]
Apparently not an issue of elm-webgl, but Elm itself doesn't support this.

**Comment by nphollon** [comment]
Yes, this has bitten me before! For a while, Advanced Closure compatibility was listed on the [projects page](https://github.com/elm-lang/projects), but it was removed around the release of 0.17

**Comment by w0rm** [comment]
@nphollon yeah, was removed in https://github.com/elm-lang/projects/commit/771e00a3a04a6f63f051405cb4e3334d9d3ea683 so I assumed it was supported, but it didn't work when I tried.
