### ISSUE TITLE
Adding Elm 0.18

### ISSUE THREAD

**Issue by rvlander** [elm-community/elm-webgl#42]
Elm 0.18 is now in beta phase but this package has not been published for it.

Is anybody working on it?

Thanks.

**Comment by w0rm** [comment]
I made it work in 0.17,  so I think I'm capable of migrating the library to 0.18.

**Comment by avh4** [comment]
Also note that https://github.com/elm-community/elm-webgl/issues/16 is meant to be done before publishing for 0.18 (that should also be easy)

**Comment by fredcy** [comment]
For the record, elm-linear-algebra has been renamed to linear-algebra in 0.18.

**Comment by w0rm** [comment]
@avh4 yeah, I've just got access to `elm-community/webgl`, so I'm on it.
