### ISSUE TITLE
Revisit open issues and pull requests from origin?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-webgl#5]
That is, go through https://github.com/johnpmayer/elm-webgl/issues and https://github.com/johnpmayer/elm-webgl/pulls and see which ones might be useful to add here?

**Comment by fredcy** [comment]
Given https://github.com/elm-community/elm-webgl/issues/6, this seems to require some process to have Evan approve each such addition as well.

**Comment by jvoigtlaender** [comment]
Evan asked for being involved only for MAJOR and MINOR changes, not for PATCH changes. So, for example, issues and pull requests that are about documentation improvements could be executed without his involvement. Same for bug fixes. In essence, everything that will only lead to a bump from version `1.0.x` to `1.0.y` should be fair game.

I didn't check at all how many of the issues and pull requests fall into such a category. Opening this issue here was really just a measure to not forget about stuff that is open at the original repository.

**Comment by nphollon** [comment]
The examples compile fine for me now that everything is at 0.16. The examples linked in the README still don't work, and I am pretty sure are a wontfix at this point (they aren't linked from the elm examples page anymore). Maybe we should just remove the links.

The only things I think might still be relevant are the issue and PR for texture filtering (https://github.com/johnpmayer/elm-webgl/pull/35 and https://github.com/johnpmayer/elm-webgl/issues/39). I haven't looked closely at this yet, but it appears to be a bug fix.

**Comment by mgold** [comment]
Number 35 seemed to have support behind it. We'd just have to not export `mapT`.

**Comment by w0rm** [comment]
I've revisited opened pull requests and [converted one](https://github.com/elm-community/webgl/pull/6) into the new repo. 

All the issues have been addressed except the ones asking for custom types in uniforms.
