### ISSUE TITLE
Respect Evan's constraints on this package

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-webgl#6]
Expressed [here](https://github.com/elm-lang/package.elm-lang.org/issues/149#issuecomment-171068020). Can this somehow be codified maybe?

**Comment by mgold** [comment]
I don't think there's a way to technically enforce what tags can be pushed, etc.

As for social enforcement, that involves everyone being aware of these constraints (keep the issue open), and then making sure someone who isn't doesn't accidentally violate them. So, perhaps as a good social norm for any elm-community project, each release should involve more than one person.

We can also ask that minor or major changes be pushed to a separate branch so they can be reviewed.

**Comment by nphollon** [comment]
I think that's a good norm to follow. (I confess I didn't follow it yesterday when tweaking the docs & elm-package.json).

It might be good to add a disclaimer to the README explaining that these packages are in maintenance-mode and probably won't accept new feature requests.

**Comment by fredcy** [comment]
Is that the case, that elm-webgl is frozen? That's a stronger position than saying that Evan has to approve any (per-semver) minor or major changes.

**Comment by mgold** [comment]
I think what @nphollon meant was that any feature request couldn't be accommodated in a patch change. We can be clearer about the wording but I agree we should add something to the README along those lines.

**Comment by nphollon** [comment]
@fredcy It's not frozen, but it isn't a high priority. I talked with Evan yesterday about getting whitelisted, and it sounds like the [upcoming API platform](https://groups.google.com/forum/#!topic/elm-dev/1JW6wknkDIo) may very well deprecate elm-webgl.

**Comment by nphollon** [comment]
I think #10 solves this.
